# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Syn8yUVXYb9ecuE5vm1MGftsFemDlFLo
"""

# app.py

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from cxloyaltyfeature import cxloyaltyfeature
from sklearn.compose import ColumnTransformer

# Load trained pipeline
pipeline = joblib.load("kmeans_pipeline.pkl")

st.title("Customer Segmentation with KMeans")

st.write("### Predict cluster for a single customer")

# --- Single customer input ---
age = st.number_input("Age", min_value=18, max_value=100, value=30)
family_size = st.number_input("Family Size", min_value=1, max_value=10, value=3)
income = st.number_input("Annual Income", min_value=10000, max_value=500000, value=50000)
cx_since = st.number_input("Customer Since (days)", min_value=1, max_value=365*10, value=365)
numdealspurchases = st.number_input("Number of Deals Purchased", min_value=0, max_value=50, value=5)
total_amnt = st.number_input("Total Amount Spent", min_value=0, max_value=100000, value=2000)
total_purchases = st.number_input("Total Purchases", min_value=0, max_value=200, value=20)
recency = st.number_input("Recency (days since last purchase)", min_value=1, max_value=365, value=30)
accepted_any_offer = st.selectbox("Accepted Any Offer?", [0, 1])

input_data = pd.DataFrame({
    'age': [age],
    'family_size': [family_size],
    'income': [income],
    'cx_since': [cx_since],
    'numdealspurchases': [numdealspurchases],
    'total_amnt': [total_amnt],
    'total_purchases': [total_purchases],
    'recency': [recency],
    'accepted_any_offer': [accepted_any_offer]
})

if st.button("Predict Single Customer Cluster"):
    cluster = pipeline.predict(input_data)
    st.success(f"Predicted Cluster: {cluster[0]}")

# --- Batch prediction via file upload ---
st.write("### Upload a CSV file for batch prediction")

uploaded_file = st.file_uploader("Upload CSV", type=["csv"])
if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.write("Preview of uploaded data:", data.head())

    if st.button("Predict Clusters for Uploaded Data"):
        clusters = pipeline.predict(data)
        data['Predicted_Cluster'] = clusters
        st.write("Results with predicted clusters:")
        st.dataframe(data)

        # Optionally allow download of results
        csv = data.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="Download predictions as CSV",
            data=csv,
            file_name="cluster_predictions.csv",
            mime="text/csv",
        )